config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  root 'questions#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  resources :users, only: %i[] do
    member do
      get :rewards
    end
  end

  resources :questions, shallow: true do
    resources :answers, shallow: true do
      member do
        post :best_mark
        post :like, defaults: { table: 'answers'}
        post :dislike, defaults: { table: 'answers'}
        post :comment, defaults: { table: 'answers'}
      end
    end

    member do
      post :like, defaults: { table: 'questions'}
      post :dislike, defaults: { table: 'questions'}
      post :comment, defaults: { table: 'questions'}
      post :subscription
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        collection do
          get :me
          get :all_others
        end
      end
    
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, shallow: true, only: %i[index show create update destroy]
      end
    end
  end

  get 'searches/index'
  post 'searches/search'

  mount ActionCable.server => '/cable'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  has_one :reward, dependent: :destroy, as: :rewardable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  default_scope { order(id: :asc) }

  validates :title, :body, presence: true

  def sorted_answers
    sotred_by_index = answers.order(id: :asc)
    if any_best?
      special_sorted = []
      sotred_by_index.each do |answer|
        answer.best? ? special_sorted.unshift(answer) : special_sorted.push(answer)
      end
      special_sorted
    else
      sotred_by_index
    end
  end

  private

  def any_best?
    answers.each do |answer|
      return true if answer.best?
    end
    false
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      def index
        authorize! :index, Question
        render json: Question.all, each_serializer: QuestionsSerializer
      end

      def show
        authorize! :show, Question
        render json: Question.find_by(id: params[:id]), serializer: QuestionSerializer
      end

      def create
        authorize! :create, Question
        title = ActionController::Base.helpers.sanitize(params[:title])
        body = ActionController::Base.helpers.sanitize(params[:body])
        Question.create(user: current_resource_user, title: title, body: body)
        head :ok
      end

      def update
        @question = Question.find_by(id: ActionController::Base.helpers.sanitize(params[:id]))
        authorize! :update, @question
        title = params[:title] ? ActionController::Base.helpers.sanitize(params[:title]) : nil
        body = params[:body] ? ActionController::Base.helpers.sanitize(params[:body]) : nil
        @question.update(
          title: title || @question.title,
          body: body || @question.body
        )
        head :ok
      end

      def destroy
        @question = Question.find_by(id: ActionController::Base.helpers.sanitize(params[:id]))
        authorize! :destroy, @question
        @question.destroy
        head :ok
      end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :find_question, only: %i[show update destroy subscription]
  after_action :publish_question, only: :create

  def index
    authorize! :index, Question
    @questions = Question.all
  end

  def show
    authorize! :show, Question
    @answer = Answer.new
    @answer.links.new
    gon.question_id = @question.id
  end

  def new
    authorize! :new, Question
    @question = Question.new
    @question.links.new
    @question.reward = Reward.new
  end

  def create
    authorize! :create, Question
    @question = current_user.questions.new(question_params)
    if @question.save
      current_user.subscriptions.create(question: @question)
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    authorize! :update, @question
    @question.update(question_params)
  end

  def destroy
    authorize! :destroy, @question
    @question.destroy
    redirect_to root_path
  end

  def subscription
    authorize! :subscription, Question
    @subscription = current_user.subscriptions.where(question: @question).first
    if @subscription.present?
      Subscription.find_by(id: @subscription.id).destroy
    else
      current_user.subscriptions.create(question: @question)
    end
  end

  private

  def find_question
    @question = Question.with_attached_files.find(params[:id])
    @comment = Comment.new
  end

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      files: [],
      links_attributes: %i[id name url _destroy],
      reward_attributes: %i[name file]
    )
  end

  def publish_question
    if @question.errors.empty?
      ActionCable.server.broadcast 'questions_index',
                                   ApplicationController.render(
                                     partial: 'questions/question_header',
                                     locals: { question: @question }
                                   )
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_link_fields.html.slim
.nested-fields
  div
    = f.label :name, 'Link name'
    br
    = f.text_field :name
  div
    = f.label :url
    br
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/questions/_new_answer.html.slim
= form_with model: [question, answer], local: false do |f|
  div
    = f.label :body
    br
    = f.text_area :body, cols: 45, rows: 1
  div
    = f.label :files
    br
    = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  p
    = f.fields_for :links do |link|
      = render 'questions/link_fields', f: link
    div
      = link_to_add_association 'add link', f, :links, partial: 'questions/link_fields'
  div
    br
    = f.submit 'Answer'

app/views/questions/_question.html.slim
div[id="questions-#{@question.id}"]
  p = @question.title
  p = @question.body
  - if @question.links.present?
    - @question.links.each do |link|
      div[id="link-#{link.id}"]
        p
          = link_to link.name, link.url
          - if can?(:destroy, link)
            |  
            = link_to octicon('x-circle'), link_path(link), method: :delete, remote: true
        - if link.gist?
          p = link_to 'Show gist content (simplified)', '#', class: "show-gist-content", data: { gist_id: link.gist_id, link_id: link.id }
          div[id="link-#{link.id}-gist-content"]
  - if @question.files.attached?
    - @question.files.each do |file|
      div[id="attachment-#{file.id}"]
        p
          = link_to file.filename.to_s, url_for(file)
          - if can?(:destroy, file)
            |  
            = link_to octicon('x-circle'), attachment_path(file), method: :delete, remote: true
  - if current_user && @question.reward.present? && @question.reward.file.attached?
    | Reward for this question: 
    = link_to @question.reward.name, url_for(@question.reward.file)
  = render 'shared/vote', resource: @question, table: 'questions'
  p
    | By: 
    = @question.user.email
  - if can?(:update, @question)
    p = link_to 'Edit the Question', '#', class: "edit-question-link", data: { question_id: @question.id }
    p = link_to 'Delete the Question', question_path(@question), method: :delete
    div[id="question-errors"]
    = form_with model: @question, class: "hide", id: "edit-question", local: false do |f|
      div
        = f.label :title, 'Edit question\'s title'
        br
        = f.text_area :title, cols: 45, rows: 1
      div
        = f.label :body, 'Edit question\'s body'
        br
        = f.text_area :body, cols: 45, rows: 1
      div
        = f.label :files
        br
        = f.file_field :files, multiple: true, direct_upload: true
      p Links:
      p
        = f.fields_for :links do |link|
          = render 'questions/link_fields', f: link
        div
          = link_to_add_association 'add link', f, :links, partial: 'questions/link_fields'
      div
        br
        = f.submit 'Update'
  - if can?(:subscription, Question) && current_user.subscribed?(@question)
    p = link_to 'Unsubscribe from the Question', subscription_question_path(@question), class: "subscription-link", method: :post, remote: true
  - elsif can?(:subscription, Question)
    p = link_to 'Subscribe to the Question', subscription_question_path(@question), class: "subscription-link", method: :post, remote: true
  = render 'shared/comments', resource: @question

app/views/questions/_question_header.html.slim
div
  h3 = question.title
  p = link_to 'Watch', question_path(question), method: :get
hr

app/views/questions/index.html.slim
span[class="page-mark questions-index-js"]

- if can?(:create, Question)
  p = link_to 'Ask question', new_question_path
- else
  | In order to ask questions please 
  = link_to 'sign in', new_user_session_path

div.questions-headers-list
  - cache collection_cache_key_for(:question) do
    - @questions.each do |question|
      = render 'question_header', question: question

app/views/questions/new.html.slim
p Create New Question

= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  div
    = f.label :title
    br
    = f.text_area :title, cols: 45, rows: 1
  div
    = f.label :body
    br
    = f.text_area :body, cols: 45, rows: 5
  div
    = f.label :files
    br
    = f.file_field :files, multiple: true, direct_upload: true
  p Reward:
  div
    = f.fields_for :reward do |r|
      div
        = r.label :name, 'Reward name'
        br
        = r.text_field :name
      div
        = r.label :file
        br
        = r.file_field :file
  p Links:
  p
    = f.fields_for :links do |link|
      = render 'questions/link_fields', f: link
    div
      = link_to_add_association 'add link', f, :links, partial: 'questions/link_fields'
  div
    br
    = f.submit 'Ask'

br
= link_to 'Back', questions_path, method: :get

app/views/questions/show.html.slim
span[class="page-mark questions-show-js"]
span.page-template
  - if current_user
    .authenticity-token-template
      input[type="hidden" name="authenticity_token" value="#{form_authenticity_token}" autocomplete="off"]

- cache @question do
  div.question-content
    div.question
      = render @question

    div.answers
      - @question.sorted_answers.each do |answer|
        = render answer

  hr
  - if current_user
    p Publicate your Answer:

    div.answer-errors
      = render 'shared/errors', resource: @answer

    - new_answer_form = render 'new_answer', question: @question, answer: @answer
    div.new-answer
      = new_answer_form
    div[class="hide blank-new-answer"]
      = new_answer_form
  - else
    | In order to publicate your answers please 
    = link_to 'sign in', new_user_session_path

hr
p = link_to 'Back', questions_path, method: :get

app/views/questions/subscription.js.erb
<% if @subscription.present? %>
  $('.subscription-link').text('Subscribe to the Question')
<% else %>
  $('.subscription-link').text('Unsubscribe from the Question')
<% end %>

app/views/questions/update.js.erb
$('#question-errors').html('<%= render 'shared/errors', resource: @question %>')

<% if @question.errors.empty? %>
  $('#questions-' + <%= @question.id %>).replaceWith('<%= j render @question %>')
<% end %>