config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  root 'questions#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  resources :users, only: %i[] do
    member do
      get :rewards
    end
  end

  resources :questions, shallow: true do
    resources :answers, shallow: true do
      member do
        post :best_mark
        post :like, defaults: { table: 'answers'}
        post :dislike, defaults: { table: 'answers'}
        post :comment, defaults: { table: 'answers'}
      end
    end

    member do
      post :like, defaults: { table: 'questions'}
      post :dislike, defaults: { table: 'questions'}
      post :comment, defaults: { table: 'questions'}
      post :subscription
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        collection do
          get :me
          get :all_others
        end
      end
    
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, shallow: true, only: %i[index show create update destroy]
      end
    end
  end

  get 'searches/index'
  post 'searches/search'

  mount ActionCable.server => '/cable'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  default_scope { order(id: :asc) }

  validates :body, presence: true

  after_create :send_notification

  private

  def send_notification
    Subscription.where(question: question).find_each(batch_size: 500) do |subscription|
      SubscriptionJob.perform_later(subscription.user, question) if question.answers.last.user != subscription.user
    end
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :find_answer, only: %i[update destroy best_mark]
  after_action :publish_answer, only: :create

  def create
    authorize! :create, Answer
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params.merge!(user: current_user))
    @comment = Comment.new
  end

  def update
    authorize! :update, @answer
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    authorize! :destroy, @answer
    @answer.destroy
  end

  def best_mark
    authorize! :best_mark, @answer
    mark_best_answer
    @answers = @answer.question.sorted_answers
  end

  private

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
    @comment = Comment.new
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[id name url _destroy])
  end

  def mark_best_answer
    @answer.question.answers.each do |answer|
      if answer == @answer
        answer.update(best: true)
        assign_reward_achievement(answer) if @answer.question.reward.present?
      elsif answer.best == true
        answer.update(best: false)
      end
    end
  end

  def assign_reward_achievement(answer)
    reward = answer.question.reward
    if reward.reward_achievement.present?
      reward.reward_achievement.update(user: answer.user)
    else
      reward.reward_achievement = RewardAchievement.create(user: answer.user, reward: reward)
    end
  end

  def publish_answer
    return unless @answer.errors.empty?

    @response = publish_answer_json_response
    add_info_to_publish_answer
    ActionCable.server.broadcast "questions_#{@answer.question.id}_show", @response
  end

  def publish_answer_json_response
    @answer.as_json(
      except: %i[created_at updated_at],
      include: {
        links: { except: %i[created_at updated_at linkable_type linkable_id] },
        files: { except: %i[created_at updated_at record_type record_id blob_id] },
        user: { only: :email },
        question: { only: :user_id }
      }
    )
  end

  def add_info_to_publish_answer
    publish_answer_links
    publish_answer_files
    publish_answer_global
  end

  def publish_answer_links
    @response['links'].each do |item|
      link = Link.find_by(id: item['id'])
      if link.gist?
        item['gist?'] = link.gist?
        item['gist_id'] = link.gist_id
      end
    end
  end

  def publish_answer_files
    @response['files'].each do |item|
      attach = ActiveStorage::Attachment.find_by(id: item['id'])
      item['name'] = attach.filename.to_s
      item['url'] = Rails.application.routes.url_helpers.rails_blob_path(attach, only_path: true)
    end
  end

  def publish_answer_global
    @response['rating'] = @answer.rating
    @response['table'] = 'answers'
    @response['controller'] = 'answers_controller'
    @response['action'] = 'create'
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnswersController < Api::V1::BaseController
      def index
        authorize! :show, Question
        render json: Answer.where(question_id: params[:question_id]), each_serializer: AnswersSerializer
      end

      def show
        authorize! :show, Question
        render json: Answer.find_by(id: params[:id]), serializer: AnswerSerializer
      end

      def create
        authorize! :create, Answer
        body = ActionController::Base.helpers.sanitize(params[:body])
        question_id = ActionController::Base.helpers.sanitize(params[:question_id])
        Answer.create(user: current_resource_user, question_id: question_id, body: body)
        head :ok
      end

      def update
        @answer = Answer.find_by(id: ActionController::Base.helpers.sanitize(params[:id]))
        authorize! :update, @answer
        body = ActionController::Base.helpers.sanitize(params[:body])
        @answer.update(body: body)
        head :ok
      end

      def destroy
        @answer = Answer.find_by(id: ActionController::Base.helpers.sanitize(params[:id]))
        authorize! :destroy, @answer
        @answer.destroy
        head :ok
      end
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div[id="answers-#{answer.id}"]
  - cache answer do
    hr
    p = answer.body
    - if answer.links.present?
      - answer.links.each do |link|
        div[id="link-#{link.id}"]
          p
            = link_to link.name, link.url
            - if can?(:destroy, link)
              |  
              = link_to octicon('x-circle'), link_path(link), method: :delete, remote: true
          - if link.gist?
            p = link_to 'Show gist content (simplified)', '#', class: "show-gist-content", data: { gist_id: link.gist_id, link_id: link.id }
            div[id="link-#{link.id}-gist-content"]
    - if answer.files.attached?
      - answer.files.each do |file|
        div[id="attachment-#{file.id}"]
          p
            = link_to file.filename.to_s, url_for(file)
            - if can?(:destroy, file)
              |  
              = link_to octicon('x-circle'), attachment_path(file), method: :delete, remote: true
    = render 'shared/vote', resource: answer, table: 'answers'
    p
      | By: 
      = answer.user.email
      div[id="answer-best-#{answer.id}"]
        = render 'answers/best', answer: answer
    - if can?(:update, answer)
      p = link_to 'Edit an Answer', '#', class: "edit-answer-link", data: { answer_id: answer.id }
      p = link_to 'Delete an Answer', answer_path(answer), method: :delete, remote: true
      div[id="answer-errors-#{answer.id}"]
      = form_with model: answer, class: "hide", id: "edit-answer-#{answer.id}", local: false do |f|
        div
          = f.label :body, 'Edit your answer'
          br
          = f.text_area :body, cols: 45, rows: 1
        div
          = f.label :files
          br
          = f.file_field :files, multiple: true, direct_upload: true
        p Links:
        p
          = f.fields_for :links do |link|
            = render 'questions/link_fields', f: link
          div
            = link_to_add_association 'add link', f, :links, partial: 'questions/link_fields'
        div
          br
          = f.submit 'Save'
    = render 'shared/comments', resource: answer

app/views/answers/_best.html.slim
- if answer.best?
  - if answer.question.reward.present?
    p Rewarded:
    p
      = answer.question.reward.name
    img[src="#{url_for(answer.question.reward.file)}"]
  - else
    p
      | *Best answer*
- elsif can?(:best_mark, answer)
    p = link_to 'Mark as best', best_mark_answer_path(answer), method: :post, remote: true

app/views/answers/best_mark.js.erb
$('.answers').html("<%= j render @answers %>")

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>')

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>')
  $('.new-answer').replaceWith($('.blank-new-answer').clone(true).attr('class', 'new-answer'))
<% end %>

app/views/answers/destroy.js.erb
$('#answers-<%= @answer.id %>').remove()

app/views/answers/update.js.erb
$('#answer-errors-<%= @answer.id %>').html('<%= render 'shared/errors', resource: @answer %>')

<% if @answer.errors.empty? %>
  $('#answers-<%= @answer.id %>').replaceWith('<%= j render @answer %>')
<% end %>