config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  root 'questions#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  resources :users, only: %i[] do
    member do
      get :rewards
    end
  end

  resources :questions, shallow: true do
    resources :answers, shallow: true do
      member do
        post :best_mark
        post :like, defaults: { table: 'answers'}
        post :dislike, defaults: { table: 'answers'}
        post :comment, defaults: { table: 'answers'}
      end
    end

    member do
      post :like, defaults: { table: 'questions'}
      post :dislike, defaults: { table: 'questions'}
      post :comment, defaults: { table: 'questions'}
      post :subscription
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        collection do
          get :me
          get :all_others
        end
      end
    
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, shallow: true, only: %i[index show create update destroy]
      end
    end
  end

  get 'searches/index'
  post 'searches/search'

  mount ActionCable.server => '/cable'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      user.admin? ? admin_abilities : user_abilities(user)
    else
      guest_abilities
    end
  end

  private

  def guest_abilities
    can %i[index show], Question
  end

  def user_abilities(user)
    can %i[index show new create comment subscription], Question
    can %i[update destroy], Question, user_id: user.id
    can %i[like dislike], Question do |votable|
      votable.user.id != user.id
    end

    can %i[create comment], Answer
    can %i[update destroy], [Answer], user_id: user.id
    can %i[like dislike], Answer do |votable|
      votable.user.id != user.id
    end
    can :best_mark, Answer do |answer|
      answer.question.user.id == user.id
    end

    can :destroy, Link do |link|
      link.linkable.user.id == user.id
    end

    can :destroy, ActiveStorage::Attachment do |attachment|
      attachment.record.user.id == user.id
    end

    can :destroy, Comment, user_id: user.id

    can %i[rewards me all_others], User
  end

  def admin_abilities
    can :manage, :all
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  default_scope { order(id: :asc) }

  validates :body, presence: true

  after_create :send_notification

  private

  def send_notification
    Subscription.where(question: question).find_each(batch_size: 500) do |subscription|
      SubscriptionJob.perform_later(subscription.user, question) if question.answers.last.user != subscription.user
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
# frozen_string_literal: true

class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, :uid, presence: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true, touch: true

  validates :body, presence: true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true, touch: true

  validates :name, :url, presence: true
  validate :validate_url

  def gist?
    url =~ %r{\Ahttps://gist.github.com} ? true : false
  end

  def gist_id
    url.split('/').reverse_each do |id|
      return id if id
    end
  end

  private

  def validate_url
    errors.add(:url, "is invalid") unless url =~ /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https])}\z/
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  has_one :reward, dependent: :destroy, as: :rewardable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  default_scope { order(id: :asc) }

  validates :title, :body, presence: true

  def sorted_answers
    sotred_by_index = answers.order(id: :asc)
    if any_best?
      special_sorted = []
      sotred_by_index.each do |answer|
        answer.best? ? special_sorted.unshift(answer) : special_sorted.push(answer)
      end
      special_sorted
    else
      sotred_by_index
    end
  end

  private

  def any_best?
    answers.each do |answer|
      return true if answer.best?
    end
    false
  end
end

app/models/reward.rb
# frozen_string_literal: true

class Reward < ApplicationRecord
  MINIMUM_REWARD_NAME_LENGTH = 5

  belongs_to :rewardable, polymorphic: true
  has_one :reward_achievement, dependent: :destroy

  has_one_attached :file

  validates :name, :file, presence: true
  validate :validate_reward_name, :validate_reward_content_type

  private

  def validate_reward_name
    return unless name && name.length < MINIMUM_REWARD_NAME_LENGTH

    errors.add(:name, "too short (minimum - #{MINIMUM_REWARD_NAME_LENGTH})")
  end

  def validate_reward_content_type
    errors.add(:content, "type is bad (allowed image only)") if file && file.content_type !~ /\Aimage/
  end
end

app/models/reward_achievement.rb
# frozen_string_literal: true

class RewardAchievement < ApplicationRecord
  belongs_to :reward
  belongs_to :user
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question, touch: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github yandex]

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :reward_achievements, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  def subscribed?(question)
    subscriptions.where(question: question).first.present? ? true : false
  end
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true, touch: true
  belongs_to :user
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_updated_at = klass.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "#{model.to_s.pluralize}/collection-#{count}-#{max_updated_at}"
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title QnA
    = Gon::Base.render_data
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    p
      - if current_user.present?
        - if current_user.admin?
          = link_to 'Sign out', destroy_user_session_path, method: :delete, style: 'background-color: green;'
        - else
          = link_to 'Sign out', destroy_user_session_path, method: :delete
        |  
        = link_to 'My Rewards', rewards_user_path(current_user)
      - else
        = link_to 'Sign up', new_user_registration_path
        |  | 
        = link_to 'Sign in', new_user_session_path
      '  
      = link_to 'Search', searches_index_path
    p class="notice"
      = notice
    p class="alert"
      = alert
    = yield

app/views/shared/_comments.html.slim
div.comments
  div.list
    - resource.comments.each do |comment|
      - cache comment do
        div[class="comments-#{comment.id}"]
          div
            = comment.body
          div
            |By: 
            = comment.user.email
            - if can?(:destroy, comment)
              |  
              = link_to 'X', comment_path(comment), method: :delete, remote: true, data: { type: :json }
          br
  div.errors
  div.new
    - if current_user
      - cache ['new-comment-form', resource] do
        = form_with model: [resource, @comment], url: eval("Rails.application.routes.url_helpers.comment_#{resource.class.name.underscore}_path(#{resource.id})"), local: false, data: { type: :json } do |f|
          div
            = f.label :body, 'Add comment'
            br
            = f.text_area :body, cols: 45, rows: 1
          div
            = f.submit 'Comment'

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b = "#{resource.errors.count} error(s) detected"
  ul
    - resource.errors.full_messages.each do |message|
      li = message

app/views/shared/_vote.html.slim
p[id="votable-#{table}-rating-#{resource.id}"]
  | Rating: 
  span[class="counter"]
    - if resource.votes.present?
      = resource.votes.where(liked: true).count - resource.votes.where(liked: false).count
    - else
      |  0 
  |  
  - if can?(:like, resource) && can?(:dislike, resource)
    - vote = resource.votes.where(user: current_user).first
    - if vote.present? && vote.liked == true
      = link_to 'Like', eval("Rails.application.routes.url_helpers.like_#{resource.class.name.underscore}_path(#{resource.id})"), method: :post, remote: true, data: { type: :json }, class: 'like-link', style: 'color: green;'
    - else
      = link_to 'Like', eval("Rails.application.routes.url_helpers.like_#{resource.class.name.underscore}_path(#{resource.id})"), method: :post, remote: true, data: { type: :json }, class: 'like-link', style: 'color: black;'
    |  / 
    - if vote.present? && vote.liked == false
      = link_to 'Dislike', eval("Rails.application.routes.url_helpers.dislike_#{resource.class.name.underscore}_path(#{resource.id})"), method: :post, remote: true, data: { type: :json }, class: 'dislike-link', style: 'color: red;'
    - else
      = link_to 'Dislike', eval("Rails.application.routes.url_helpers.dislike_#{resource.class.name.underscore}_path(#{resource.id})"), method: :post, remote: true, data: { type: :json }, class: 'dislike-link', style: 'color: black;'

app/views/shared/_votes.html.slim
p[id="votable-rating-#{resource.id}"]
  | Rating: 
  span[class="counter"]
    - if resource.votes.present?
      = resource.votes.where(liked: true).count - resource.votes.where(liked: false).count
    - else
      |  0 
  |  
  - if current_user.present? && resource.user != current_user
    - vote = resource.votes.where(user: current_user).first
    - if vote.present? && vote.liked == true
      = link_to 'Like', eval("Rails.application.routes.url_helpers.like_#{resource.class.name.underscore}_path(#{resource.id})"), method: :post, remote: true, data: { type: :json }, class: 'like-link', style: 'color: green;'
    - else
      = link_to 'Like', eval("Rails.application.routes.url_helpers.like_#{resource.class.name.underscore}_path(#{resource.id})"), method: :post, remote: true, data: { type: :json }, class: 'like-link', style: 'color: black;'
    |  / 
    - if vote.present? && vote.liked == false
      = link_to 'Dislike', eval("Rails.application.routes.url_helpers.dislike_#{resource.class.name.underscore}_path(#{resource.id})"), method: :post, remote: true, data: { type: :json }, class: 'dislike-link', style: 'color: red;'
    - else
      = link_to 'Dislike', eval("Rails.application.routes.url_helpers.dislike_#{resource.class.name.underscore}_path(#{resource.id})"), method: :post, remote: true, data: { type: :json }, class: 'dislike-link', style: 'color: black;'